AzureChampionship/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AzureChampionship.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AzureChampionship/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Azure.Devices.Client;
using Newtonsoft.Json;
using System.Text;
using System.Threading;
using System.IO;
using System.Data.Odbc;
using RestSharp;
using Newtonsoft.Json.Linq;


namespace AzureChampionship.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }


        //Starts the simulation
        public IActionResult OnPostStart()
        {

            //simulation connections
            Console.WriteLine("\nIoT Hub Simulated Sensor Data Has started:");

            FetchApiDataAsync();

            // Connect to the IoT hub using the MQTT protocol
            s_deviceClient = DeviceClient.CreateFromConnectionString(s_connectionString, TransportType.Mqtt);
            SendDeviceToCloudMessagesAsync();

            return Page();
        }


        //instantaites devvice client string connection
        private static DeviceClient s_deviceClient;

        // The device connection string to authenticate the device with your IoT hub.
        private readonly static string s_connectionString = "HostName=gclawsonTempSensorHub.azure-devices.net;DeviceId=gclawson_mxchip;SharedAccessKey=egxteVKHF5+oypQALbXImcKQL1RM0edtnKglT/RBmNM=";

        //Async method to send simulated telemetry - Async to allow other processes to take place during data send
        public async void SendDeviceToCloudMessagesAsync()
        {

            Random rand = new Random();
            // Initial telemetry values
            double minRoom = 20;

            int i = 0;

            while (true)
            {

                i++;

                double currentRoom1 = minRoom + rand.NextDouble() * 11;
                double currentRoom2 = minRoom + rand.NextDouble() * 12;
                double currentRoom3 = minRoom + rand.NextDouble() * 13;
                double currentRoom4 = minRoom + rand.NextDouble() * 14;
                double currentRoom5 = minRoom + rand.NextDouble() * 15;
                double currentRoom6 = minRoom + rand.NextDouble() * 16;
                double currentRoom7 = minRoom + rand.NextDouble() * 15;
                double currentRoom8 = minRoom + rand.NextDouble() * 14;
                double currentRoom9 = minRoom + rand.NextDouble() * 13;
                double currentRoom10 = minRoom + rand.NextDouble() * 12;
                double currentRoom11 = minRoom + rand.NextDouble() * 11;
                double currentRoom12 = minRoom + rand.NextDouble() * 10;

                // Create JSON message
                var telemetryDataPoint = new
                {
                    room1 = currentRoom1,
                    room2 = currentRoom2,
                    room3 = currentRoom3,
                    room4 = currentRoom4,
                    room5 = currentRoom5,
                    room6 = currentRoom6,
                    room7 = currentRoom7,
                    room8 = currentRoom8,
                    room9 = currentRoom9,
                    room10 = currentRoom10,
                    room11 = currentRoom11,
                    room12 = currentRoom12,

                };

                var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
                var message = new Message(Encoding.ASCII.GetBytes(messageString));

                // Add a custom application property to the message.
                // An IoT hub can filter on these properties without access to the message body.
                message.Properties.Add("room1Alert", (currentRoom1 > 30) ? "true" : "false");

                // Send the telemetry message
                await s_deviceClient.SendEventAsync(message);
                //Console.WriteLine("\n{0} > Sending Message: {1}", DateTime.Now, messageString);

 
                if (i >= 1) // number of iterations of data send
                {
                    //Console.WriteLine("Completed sending messages\n");
                    break;
                }

                await Task.Delay(1000); //1000 = 1 second delay

            }

        }

        public async void FetchApiDataAsync()
        {
            int i = 0;

            while (true)
            {

                //fetches sensor data from the RESTful API connectde to the CosmosDB
                FetchData();

                i++;

                if (i >= 1) // number of iterations of data send
                {
                    Console.WriteLine("\nIoT Hub Simulated Sensor Data Has stopped.\n");
                    break;
                }

                await Task.Delay(1000); //1000 = 1 second delay

            }

        }

        //Parses fetched json and dipslays selected elements
        public void FetchData()
        {

            //RESTful API url where our sensor data sits
            string url = "https://gclawsontempsensor.azurewebsites.net/api/temperature/%7Bdevicename%7D";

            //Use Restsharp to fetch data form url 
            string data = GetReleases(url);
            //Console.WriteLine(data);

            var newString = data.Substring(1, data.Length - 2); //removes sqwuare btrackets from front and end of json 
            //Console.WriteLine("\n\n\n{0}", newString);

            //pares json into c# object so we can pick elements from it to display
            JObject stuff = JObject.Parse(newString);
            //Console.WriteLine("\n\n\n{0}", stuff);

            //Select element from json object to display
            string room1 = (string)stuff["Temperature_Data"]["room1"];
            Console.WriteLine("\nRoom 1: {0}", room1);
            ViewData["room1SensorValue"] = room1;

            string room2 = (string)stuff["Temperature_Data"]["room2"];
            Console.WriteLine("Room 2: {0}", room2);
            ViewData["room2SensorValue"] = room2;

            string room3 = (string)stuff["Temperature_Data"]["room3"];
            Console.WriteLine("Room 3: {0}", room3);
            ViewData["room3SensorValue"] = room3;

            string room4 = (string)stuff["Temperature_Data"]["room4"];
            Console.WriteLine("Room 4: {0}", room4);
            ViewData["room4SensorValue"] = room4;

            string room5 = (string)stuff["Temperature_Data"]["room5"];
            Console.WriteLine("Room 5: {0}", room5);
            ViewData["room5SensorValue"] = room5;

            string room6 = (string)stuff["Temperature_Data"]["room6"];
            Console.WriteLine("Room 6: {0}", room6);
            ViewData["room6SensorValue"] = room6;

            string room7 = (string)stuff["Temperature_Data"]["room7"];
            Console.WriteLine("Room 7: {0}", room7);
            ViewData["room7SensorValue"] = room7;

            string room8 = (string)stuff["Temperature_Data"]["room8"];
            Console.WriteLine("Room 8: {0}", room8);
            ViewData["room8SensorValue"] = room8;

            string room9 = (string)stuff["Temperature_Data"]["room9"];
            Console.WriteLine("Room 9: {0}", room9);
            ViewData["room9SensorValue"] = room9;

            string room10 = (string)stuff["Temperature_Data"]["room10"];
            Console.WriteLine("Room 10: {0}", room10);
            ViewData["room10SensorValue"] = room10;

            string room11 = (string)stuff["Temperature_Data"]["room11"];
            Console.WriteLine("Room 11: {0}", room11);
            ViewData["room11SensorValue"] = room11;

            string room12 = (string)stuff["Temperature_Data"]["room12"];
            Console.WriteLine("Room 12: {0}", room12);
            ViewData["room12SensorValue"] = room12;

        }


        //Fecthes sensor data from RESTful API and returns reponse
        public static string GetReleases(string url)
        {
            var client = new RestClient(url);

            var response = client.Execute(new RestRequest());

            return response.Content;
        }

    }
    
}

AzureChampionship/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AzureChampionship.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AzureChampionship/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="css/navbar.css">
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">

    <!-- Data ingested link: https://gclawsontempsensor.azurewebsites.net/api/temperature/{devicename} -->
    <!-- Website link: https://azurechampionship.azurewebsites.net -->

</head>

<body>

    <Section class="navBar">
        <header>
            <div class="container">
                <h1 class="logo"></h1>

                <nav>
                    <ul>
                        <li><a href="https://certmatters.com/wp-content/uploads/2020/06/Azure-Fundamentals-Championship-Brief-030620.pdf">Azure Championship 2020 Details</a></li>
                    </ul>
                </nav>
            </div>
        </header>
    </Section>


    <!-- //Header -->
    <section class="header">

        <h1>FlowBio</h1>
        <h2>- Azure Championship 2020 -</h2>
        <h2> Callum Thompson & Garry Clawson </h2>

    </section>

    <!-- // Action buttons  -->

    <div class="header">
        <form method="POST">
            <button type="submit" class="btn btn-success" asp-page-handler="start">Press to Simulate</button>
        </form>

    </div>

    <!-- // Description of example-->

    <div class="description">

        <h1>Example simulated environment showing warning conditions using realtime ingested data from 12 simulated IoT devices.</h1>

    </div>


    <div class="floorPlan">
        <!--Test IMageMap property -->

        <img src="assets/floorPlan.png" class="image">

            <div class="circleRoom1" id="Room1"></div>
            <div class="circleRoom2" id="Room2"></div>
            <div class="circleRoom3" id="Room3"></div>
            <div class="circleRoom4" id="Room4"></div>
            <div class="circleRoom5" id="Room5"></div>
            <div class="circleRoom6" id="Room6"></div>
            <div class="circleRoom7" id="Room7"></div>
            <div class="circleRoom8" id="Room8"></div>
            <div class="circleRoom9" id="Room9"></div>
            <div class="circleRoom10" id="Room10"></div>
            <div class="circleRoom11" id="Room11"></div>
            <div class="circleRoom12" id="Room12"></div>

        </div>



        <!-- // Description of algorithm -->

        <div class="description1">

            <h1>Removing contaminated air using pathfinding algorithms such as A*.</h1>

        </div>

        <!-- //  video of A* algorithm -->

        <div class="video">



            <img src="assets/Astar.gif" class="image">

        </div>



</body>

</html>

<script>
// Listen to scroll event for window

    console.log("Page Loaded :)");


    //Room sensors values passed from backend c#

    var room1SensorValue = @Html.Raw(Json.Serialize(ViewData["room1SensorValue"]));
    console.log("Room 1 sensor value", room1SensorValue);

    var room2SensorValue = @Html.Raw(Json.Serialize(ViewData["room2SensorValue"]));
    console.log("Room 2 sensor value", room2SensorValue);

    var room3SensorValue = @Html.Raw(Json.Serialize(ViewData["room3SensorValue"]));
    console.log("Room 3 sensor value", room3SensorValue);

    var room4SensorValue = @Html.Raw(Json.Serialize(ViewData["room4SensorValue"]));
    console.log("Room 4 sensor value", room4SensorValue);

    var room5SensorValue = @Html.Raw(Json.Serialize(ViewData["room5SensorValue"]));
    console.log("Room 5 sensor value", room5SensorValue);

    var room6SensorValue = @Html.Raw(Json.Serialize(ViewData["room6SensorValue"]));
    console.log("Room 6 sensor value", room6SensorValue);

    var room7SensorValue = @Html.Raw(Json.Serialize(ViewData["room7SensorValue"]));
    console.log("Room 7 sensor value", room7SensorValue);

    var room8SensorValue = @Html.Raw(Json.Serialize(ViewData["room8SensorValue"]));
    console.log("Room 8 sensor value", room8SensorValue);

    var room9SensorValue = @Html.Raw(Json.Serialize(ViewData["room9SensorValue"]));
    console.log("Room 9 sensor value", room9SensorValue);

    var room10SensorValue = @Html.Raw(Json.Serialize(ViewData["room10SensorValue"]));
    console.log("Room 10 sensor value", room10SensorValue);

    var room11SensorValue = @Html.Raw(Json.Serialize(ViewData["room11SensorValue"]));
    console.log("Room 11 sensor value", room11SensorValue);

    var room12SensorValue = @Html.Raw(Json.Serialize(ViewData["room12SensorValue"]));
    console.log("Room 12 sensor value", room12SensorValue);



    //Note used - time interval to collect room sensor data from backend

    var sensorTime = 1;

    var interval = setInterval(function () {
        if (sensorTime <= 5) {
            sensorTime++;

        }
        else {
            clearInterval(interval);
        }
    }, 1000);






    //time interval to change colour every 1 second for 60 seconds

    var time = 1;

    var interval = setInterval(function () {
        if (time <= 60) {
            time++;

            //change colours

            document.getElementById("Room1").style.backgroundColor = getRoomColor(room1SensorValue);
            document.getElementById("Room1").style.transform = getCircleSize(room1SensorValue);

            document.getElementById("Room2").style.backgroundColor = getRoomColor(room2SensorValue);
            document.getElementById("Room2").style.transform = getCircleSize(room2SensorValue);

            document.getElementById("Room3").style.backgroundColor = getRoomColor(room3SensorValue);
            document.getElementById("Room3").style.transform = getCircleSize(room3SensorValue);

            document.getElementById("Room4").style.backgroundColor = getRoomColor(room4SensorValue);
            document.getElementById("Room4").style.transform = getCircleSize(room4SensorValue);

            document.getElementById("Room5").style.backgroundColor = getRoomColor(room5SensorValue);
            document.getElementById("Room5").style.transform = getCircleSize(room5SensorValue);

            document.getElementById("Room6").style.backgroundColor = getRoomColor(room6SensorValue);
            document.getElementById("Room6").style.transform = getCircleSize(room6SensorValue);

            document.getElementById("Room7").style.backgroundColor = getRoomColor(room7SensorValue);
            document.getElementById("Room7").style.transform = getCircleSize(room7SensorValue);

            document.getElementById("Room8").style.backgroundColor = getRoomColor(room8SensorValue);
            document.getElementById("Room8").style.transform = getCircleSize(room8SensorValue);

            document.getElementById("Room9").style.backgroundColor = getRoomColor(room9SensorValue);
            document.getElementById("Room9").style.transform = getCircleSize(room9SensorValue);

            document.getElementById("Room10").style.backgroundColor = getRoomColor(room10SensorValue);
            document.getElementById("Room10").style.transform = getCircleSize(room10SensorValue);

            document.getElementById("Room11").style.backgroundColor = getRoomColor(room11SensorValue);
            document.getElementById("Room11").style.transform = getCircleSize(room11SensorValue);

            document.getElementById("Room12").style.backgroundColor = getRoomColor(room12SensorValue);
            document.getElementById("Room12").style.transform = getCircleSize(room12SensorValue);


        }
        else {
            clearInterval(interval);
        }
    }, 1000);



    function getRoomColor(roomColor) {

        if (roomColor < 24) {

            color = '#7CFC00';

        } else if (roomColor > 23 && roomColor < 26) {

            color = '#FFA500';

        } else if (roomColor > 25 && roomColor < 35) {

            color = '#FF0000';
        }

        return color;
    }

    function getCircleSize(circleSize) {

        if (circleSize < 24) {

            size = 'scale(1.0, 1.0)';

        } else if (circleSize > 23 && circleSize < 26) {

            size = 'scale(1.1, 1.1)';

        } else if (circleSize > 25 && circleSize < 35) {

            size = 'scale(1.2, 1.2)';
        }

        return size;
    }







</script>